const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const L=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}},S=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const rs=n=>'₹'+n.toLocaleString('en-IN'),SZ=['XS','S','M','L','XL'];
window.fb=e=>{e.onerror=null;e.src='data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 500"><rect width="400" height="500" fill="#2a2826"/><text x="200" y="250" fill="#b08d57" font-family="Georgia" font-size="34" text-anchor="middle" letter-spacing="8">ELTORA</text><text x="200" y="285" fill="#c9b79c" font-family="Georgia" font-size="13" text-anchor="middle">${(e.alt||'').replace(/[<&"]/g,'')}</text></svg>`)};
const im=(s,a,p)=>`<img src="${s}" alt="${a}"${p?` style="object-position:${p}"`:''} loading="lazy" onerror="fb(this)">`;
const M={"p": ["assets/images/products/p1.png", "assets/images/products/p2.png", "assets/images/products/p3.png", "assets/images/products/p4.png", "assets/images/products/p5.png", "assets/images/products/p6.png", "assets/images/products/p7.png", "assets/images/products/p8.png"], "c": ["assets/images/collections/c1.jpg", "assets/images/collections/c2.jpg", "assets/images/collections/c3.jpg", "assets/images/collections/c4.jpg", "assets/images/collections/c5.jpg"], "sig": "assets/images/collections/signature.png", "l": ["assets/images/lookbook/look1.jpg", "assets/images/lookbook/look2.jpg"], "e": ["assets/images/editorial/e1.png", "assets/images/editorial/e2.jpg", "assets/images/editorial/e3.jpg"], "about": "assets/images/lifestyle/about.jpg"};
const P=[['Silk Evening Dress','Evening','Signature',8999,['Champagne'],'2026-09-01',0,5],['Noir Satin Dress','Women','Noir Edit',6499,['Black'],'2026-08-20',0,5],['Azure Tulle Gown','Evening','Signature',12999,['Blue'],'2026-09-10',0,4],['Sculpted Blazer','Men','Modern Essentials',8999,['Beige'],'2026-07-15',1,5],['Velvet Statement Dress','Occasion','Evening Edit',8999,['Red'],'2026-08-05',0,5],['Noir Sheer Saree','Women','Signature',4999,['Black'],'2026-06-30',0,5],['Champagne Dress','Occasion','Evening Edit',6499,['Champagne'],'2026-09-15',0,3],['Modern Luxe Set','Men','Modern Essentials',12999,['Black'],'2026-07-01',2,5]]
.map((a,i)=>({id:i+1,name:'ELTORA '+a[0],cat:a[1],coll:a[2],price:a[3],colors:a[4],date:a[5],sizes:SZ.slice(a[6],a[7]),img:M.p[i]}));
let C=L('el-cart',[]),W=L('el-wish',[]),cur=null;
const uniq=k=>[...new Set(P.flatMap(p=>[].concat(p[k])))];
const sel=(id,l,o)=>`<select id="${id}" aria-label="${l}"><option value="">${l}</option>${o.map(x=>Array.isArray(x)?`<option value="${x[0]}">${x[1]}</option>`:`<option>${x}</option>`).join('')}</select>`;
$('#bar').innerHTML=`<input id="q" type="search" placeholder="Search by name, category or collection" aria-label="Search">`+sel('fc','Category',uniq('cat'))+sel('fp','Price',[['a','Under ₹6,000'],['b','₹6,000 to ₹9,000'],['c','Above ₹9,000']])+sel('fs','Size',SZ)+sel('fo','Color',uniq('colors'))+sel('fl','Collection',uniq('coll'))+`<select id="so" aria-label="Sort"><option value="">Featured</option><option value="new">Newest</option><option value="lo">Price: Low to High</option><option value="hi">Price: High to Low</option></select>`;
const card=p=>`<article class="card rv"><div class="ph"><a href="#" data-o="${p.id}">${im(p.img,p.name)}</a><button class="wl${W.includes(p.id)?' on':''}" data-w="${p.id}" aria-label="Wishlist">♡</button><button class="qv" data-q="${p.id}">Quick View</button></div><h3>${p.name}</h3><p class="m">${p.cat} · ${rs(p.price)}</p><button class="btn sm" data-a="${p.id}">Add to Cart</button></article>`;
function list(){const q=$('#q').value.toLowerCase(),c=$('#fc').value,pr=$('#fp').value,s=$('#fs').value,co=$('#fo').value,cl=$('#fl').value,o=$('#so').value;
const r=P.filter(p=>(!q||(p.name+p.cat+p.coll).toLowerCase().includes(q))&&(!c||p.cat==c)&&(!co||p.colors.includes(co))&&(!s||p.sizes.includes(s))&&(!cl||p.coll==cl)&&(!pr||(pr=='a'?p.price<6000:pr=='b'?p.price>=6000&&p.price<=9000:p.price>9000)));
r.sort(o=='lo'?(a,b)=>a.price-b.price:o=='hi'?(a,b)=>b.price-a.price:o=='new'?(a,b)=>b.date.localeCompare(a.date):(a,b)=>a.id-b.id);
$('#grid').innerHTML=r.map(card).join('')||'<p>No pieces match. Clear a filter or search another name.</p>';reveal()}
$('#bar').addEventListener('input',list);
function filt(f){['q','fc','fp','fs','fo','fl','so'].forEach(i=>$('#'+i).value='');if(f=='new')$('#so').value='new';else if(['Women','Men'].includes(f))$('#fc').value=f;else if(f)$('#fl').value=f;list()}
/* cart and wishlist */
const cnt=()=>{$('#cc').textContent=C.reduce((a,l)=>a+l.qty,0);$('#wc').textContent=W.length};
const save=()=>{S('el-cart',C);S('el-wish',W);cnt()};
const find=id=>P.find(p=>p.id==id);
function add(id,size,color,qty=1){const p=find(id);size=size||(p.sizes.includes('M')?'M':p.sizes[0]);color=color||p.colors[0];const l=C.find(x=>x.id==id&&x.size==size&&x.color==color);l?l.qty+=qty:C.push({id:+id,size,color,qty});save()}
function drawer(h){$('#cd').innerHTML=`<button data-x2>Close</button>`+h;$('#cd').classList.add('o')}
function cart(){const t=C.reduce((a,l)=>a+l.qty*find(l.id).price,0);drawer(`<h2>Your Cart</h2>`+(C.length?C.map((l,i)=>{const p=find(l.id);return`<div class="ln"><div class="ph">${im(p.img,p.name)}</div><div><b>${p.name}</b><small>${l.size} · ${l.color} · ${rs(p.price)}</small><button data-cm="${i}" aria-label="Decrease">−</button>${l.qty}<button data-cp="${i}" aria-label="Increase">+</button><button data-cr="${i}">Remove</button><small>Subtotal ${rs(p.price*l.qty)}</small></div></div>`}).join('')+`<p class="pr">Total ${rs(t)}</p><button class="btn" data-co>Checkout (demo)</button>`:'<p>Your cart is empty. Add a piece from New Arrivals.</p>'))}
function wish(){drawer(`<h2>Wishlist</h2>`+(W.length?W.map(id=>{const p=find(id);return`<div class="ln"><div class="ph">${im(p.img,p.name)}</div><div><b>${p.name}</b><small>${rs(p.price)}</small><button data-a="${id}">Add to Cart</button><button data-w="${id}">Remove</button></div></div>`}).join(''):'<p>Nothing saved yet. Tap the heart on any piece.</p>'))}
/* modal */
function show(id,full){const p=cur=find(id);$('#dm').innerHTML=`<button class="x" data-x>Close</button><div class="md"><div class="mi">${im(p.img,p.name)}</div><div class="mt"><h2>${p.name}</h2><p class="pr">${rs(p.price)}</p><p>A precisely cut ${p.cat.toLowerCase()} piece from the ${p.coll} collection, made to move with you and hold its line all evening.</p><div class="ch" id="sz">${p.sizes.map(s=>`<button class="${s==(p.sizes.includes('M')?'M':p.sizes[0])?'on':''}">${s}</button>`).join('')}</div><div class="ch" id="co">${p.colors.map((c,i)=>`<button class="${i?'':'on'}">${c}</button>`).join('')}</div><div class="qt"><button data-qm aria-label="Decrease">−</button><b id="qn">1</b><button data-qp aria-label="Increase">+</button></div><button class="btn" data-ad>Add to Cart</button>${full?'<button class="btn ghost" data-by>Buy Now</button>':''}<button class="btn ghost" data-w="${p.id}">${W.includes(p.id)?'Remove from Wishlist':'Add to Wishlist'}</button>${full?`<details open><summary>Product details</summary><p>Tailored fit, concealed fastening, fully lined.</p></details><details><summary>Fabric</summary><p>Demo copy: premium woven blend with a soft, fluid drape.</p></details><details><summary>Care</summary><p>Dry clean recommended. Steam to remove creases.</p></details><details><summary>Shipping</summary><p>Free demo shipping across India in 3 to 5 days.</p></details>`:`<a href="#" data-o="${p.id}">View full details</a>`}</div></div>`;if(!$('#dlg').open)$('#dlg').showModal()}
const pick=()=>({s:$('#sz .on')?.textContent,c:$('#co .on')?.textContent,q:+$('#qn').textContent});
function checkout(){$('#cd').classList.remove('o');$('#dm').innerHTML=`<button class="x" data-x>Close</button><form class="mt" id="cf"><h2>Checkout</h2><p class="note">Demo checkout. No payment is taken and no order is placed.</p><input required placeholder="Full name" aria-label="Full name"><input type="email" required placeholder="Email" aria-label="Email"><input required placeholder="Delivery address" aria-label="Address"><b class="pr">Total ${rs(C.reduce((a,l)=>a+l.qty*find(l.id).price,0))}</b><button class="btn">Place demo order</button></form>`;if(!$('#dlg').open)$('#dlg').showModal()}
document.addEventListener('click',e=>{const t=e.target,g=a=>t.closest(`[${a}]`),d=a=>g(a)?.getAttribute(a);
if(d('data-f')!=null)filt(d('data-f'));
if(g('data-o')){e.preventDefault();show(d('data-o'),true)}else if(g('data-q'))show(d('data-q'));
else if(g('data-w')){const id=+d('data-w');W=W.includes(id)?W.filter(x=>x!=id):[...W,id];save();$$(`.wl[data-w="${id}"]`).forEach(b=>b.classList.toggle('on',W.includes(id)));if($('#cd').classList.contains('o')&&$('#cd h2')?.textContent=='Wishlist')wish();if($('#dlg').open&&cur?.id==id&&$('[data-ad]'))show(id,!!$('details'))}
else if(g('data-a')){add(d('data-a'));cart()}
else if(g('data-ad')){const k=pick();add(cur.id,k.s,k.c,k.q);$('#dlg').close();cart()}
else if(g('data-by')){const k=pick();add(cur.id,k.s,k.c,k.q);checkout()}
else if(g('data-qm')){const n=$('#qn');n.textContent=Math.max(1,+n.textContent-1)}else if(g('data-qp')){const n=$('#qn');n.textContent=Math.min(9,+n.textContent+1)}
else if(t.closest('.ch button')){t.parentNode.querySelectorAll('button').forEach(b=>b.classList.remove('on'));t.classList.add('on')}
else if(g('data-cm')){const l=C[d('data-cm')];l.qty>1?l.qty--:C.splice(d('data-cm'),1);save();cart()}else if(g('data-cp')){C[d('data-cp')].qty++;save();cart()}else if(g('data-cr')){C.splice(d('data-cr'),1);save();cart()}
else if(g('data-co'))checkout();else if(g('data-x'))$('#dlg').close();else if(g('data-x2'))$('#cd').classList.remove('o');
if(t.id=='dlg')t.close();
if(t.closest('#menu a'))$('#menu').classList.remove('o')});
$('#bC').onclick=cart;$('#bW').onclick=wish;$('#burger').onclick=()=>$('#menu').classList.toggle('o');
$('#bS').onclick=()=>{$('#shop').scrollIntoView();setTimeout(()=>$('#q').focus(),400)};
$('#bA').onclick=()=>{$('#dm').innerHTML=`<button class="x" data-x>Close</button><form class="mt" id="af"><h2>Account</h2><p class="note">Demo sign in. Nothing is stored or sent.</p><input type="email" required placeholder="Email" aria-label="Email"><input type="password" required placeholder="Password" aria-label="Password"><button class="btn">Sign in</button></form>`;$('#dlg').showModal()};
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target;
if(f.id=='cf'){C=[];save();f.innerHTML=`<h2>Thank you</h2><p>Demo order ELT-${Date.now().toString().slice(-6)} recorded. No payment was taken.</p><button class="btn" data-x>Close</button>`}
else if(f.id=='af')$('#dlg').close();else if(f.id=='nf'){f.innerHTML='<p>You are on the list. Welcome to ELTORA.</p>'}});
/* editorial sections filled from image manifests */
const cats=[['Women','Women'],['Men','Men'],['New Arrivals','new'],['Evening Wear','Evening'],['Occasion Wear','Occasion']];
$('#cats').innerHTML=cats.map((c,i)=>`<a class="cat rv" href="#shop" data-f="${c[1]}">${im(M.c[i],c[0],i==2?'50% 50%':'')}<span>${c[0]}<i>→</i></span></a>`).join('');
$('#looks').innerHTML=[1,2].map(n=>`<section class="sig"><div class="px">${im(M.l[n-1],'Look 0'+n,['50% 8%','50% 14%'][n-1])}</div><div class="in"><h2>Look 0${n}</h2><a class="btn ghost mag" href="#shop">Shop the look</a></div></section>`).join('');
$('#ed').innerHTML=[['The Evening Edit','Silhouettes for after dark.'],['Modern Essentials','Everyday pieces that last.'],['The Art of Dressing','Fit, fabric and finishing.']].map((s,i)=>`<article class="rv"><div class="ph">${im(M.e[i],s[0],'50% 10%')}</div><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('');
/* motion */
const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('v');io.unobserve(x.target)}}),{threshold:.1});
function reveal(){$$('.rv:not(.v)').forEach(x=>io.observe(x))}
addEventListener('scroll',()=>{$('#nav').classList.toggle('s',scrollY>60);if(!matchMedia('(prefers-reduced-motion:reduce)').matches)$$('.px img').forEach(i=>{const r=i.parentNode.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)i.style.transform=`translateY(${(r.top-innerHeight/2)*-.05}px) scale(1.12)`})},{passive:true});
$$('.mag').forEach(b=>{b.onmousemove=e=>{const r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.2}px,${(e.clientY-r.top-r.height/2)*.3}px)`};b.onmouseleave=()=>b.style.transform=''});
list();cnt();reveal();
